### ISSUE TITLE
UnboundLocalError: local variable 'raw_data' referenced before assignment

### ISSUE THREAD

**Issue by utdrmac** [BitBotFactory/MikaLendingBot#591]
This is new. Just restarted the bot after switching VPNs. No other changes.

```
root@gasgiant:/usr/src/bitfinex# python lendingbot.py
Starting WebServer at 10.10.10.202 on port 8001 with template www
Started WebServer, lendingbot status available at http://10.10.10.202:8001/lendingbot.html
Welcome to "Bitfinex Lending Bot" on BITFINEX
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/src/bitfinex/modules/MarketAnalysis.py", line 178, in update_market_thread
    market_data.append(str(raw_data[i]['rate']))
UnboundLocalError: local variable 'raw_data' referenced before assignment
```

**Comment by laxdog** [comment]
Happens when it doesn't get data from the DB in analysis mode. 

Did it go away?
