### ISSUE TITLE
Connection Error when requesting offers from Bitfinex

### ISSUE THREAD

**Issue by chfast** [BitBotFactory/MikaLendingBot#599]
```
2017-12-26 12:34:22 Error ('Connection aborted.', error(0, 'Error')) Requesting https://api.bitfinex.com/v1/offers
Traceback (most recent call last):
  File "lendingbot.py", line 93, in <module>
    Lending.cancel_all()
  File "/home/pi/poloniexlendingbot/modules/Lending.py", line 195, in cancel_all
    loan_offers = api.return_open_loan_offers()
  File "/home/pi/poloniexlendingbot/modules/Bitfinex.py", line 140, in return_open_loan_offers
    bfx_resp = self._post('offers')
  File "/home/pi/poloniexlendingbot/modules/ExchangeApi.py", line 29, in new_method
    return method(self, *arg, **kws)
  File "/home/pi/poloniexlendingbot/modules/Bitfinex.py", line 110, in _post
    return self._request('post', payload['request'], signed_payload, verify)
  File "/home/pi/poloniexlendingbot/modules/Bitfinex.py", line 99, in _request
    raise ex
ConnectionError: ('Connection aborted.', error(0, 'Error'))

v315
 Unhandled error, please open a Github issue so we can fix it!
```

**Comment by laxdog** [comment]
Is this an ongoing problem @chfast ?
