### ISSUE TITLE
KeyError: u'USD_GBP'

### ISSUE THREAD

**Issue by kristapsk** [BitBotFactory/MikaLendingBot#629]
From time to time I get this:
```
Error USD_GBP
Traceback (most recent call last):
  File "./lendingbot.py", line 114, in <module>
    Lending.lend_all()
  File "***/poloniexlendingbot/modules/Lending.py", line 252, in lend_all
    usable_currencies += lend_cur(cur, total_lent, lending_balances, ticker)
  File "***/modules/Lending.py", line 475, in lend_cur
    raise msg
KeyError: u'USD_GBP'

v326
 Unhandled error, please open a Github issue so we can fix it!
```

I have manually added EUR and GBP to BITFINEX.all_currencies in default.cfg.

**Comment by Evanito** [comment]
May be caused when trying to find rates when none are available on Bitfinex?

**Comment by tuberculo** [comment]
Probably related to #589.
