### ISSUE TITLE
KeyError: 'USD_BTC'

### ISSUE THREAD

**Issue by meriajokas** [BitBotFactory/MikaLendingBot#643]
Lending EUR in Bitfinex, sometimes this error comes up. Any idea what it is about? Lending does seem to work fine though (atm I'm only lending EUR, not USD or BTC). 

Traceback (most recent call last):
  File "lendingbot.py", line 114, in <module>
    Lending.lend_all()
  File "/home/pi/poloniexlendingbot/modules/Lending.py", line 252, in lend_all
    usable_currencies += lend_cur(cur, total_lent, lending_balances, ticker)
  File "/home/pi/poloniexlendingbot/modules/Lending.py", line 475, in lend_cur
    raise msg
KeyError: 'USD_BTC'

v327
 Unhandled error, please open a Github issue so we can fix it!

**Comment by meriajokas** [comment]
It seems that this issue was due to the minloansize being less than what is accepted by the exchange. After setting it to 50 the issue has not come up again.
